version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "example.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'

  celery:
    build: .
    command: celery worker -l info -A example.blueprints.bptest2.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/app'

volumes:
  redis:
